### ISSUE TITLE
Add One Dark Pro Theme

### ISSUE THREAD

**Issue by tonix-tuft** [PrismJS/prism-themes#100]
Hi guys, and thank you for this repo!

Are there any plans about adding new dark themes? Themes like, for example, the Atom's One Dark Pro Theme, which looks like this and is pretty cool:

![image](https://user-images.githubusercontent.com/10134421/81067817-94970d80-8edf-11ea-8161-28ba9ee5e480.png)

https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme

Thank you for your attention.

**Comment by mAAdhaTTah** [comment]
Yup! We gladly accept pull requests for new themes.

**Comment by tonix-tuft** [comment]
Sounds intriguing, will try to set it up and send a PR. Thank you!

**Comment by RunDevelopment** [comment]
Resolved by #130.
