### ISSUE TITLE
External chain does not support

### ISSUE THREAD

**Issue by fish-uncle** [PrismJS/prism-themes#101]
```
custom_css: 'https://cdn.example.com/prism-tomorrow.css'
```

**Comment by RunDevelopment** [comment]
Please describe your issue in more detail.

**Comment by fish-uncle** [comment]
I want to use my own CDN CSS
But there is no configuration
`custom_css` is Relative path
```
const prismThemeFilePath = custom_css === null ? prismTheme.path : path.join(hexo.base_dir, custom_css);
```

**Comment by RunDevelopment** [comment]
Some clarification before we continue:
Prism and Prism-themes only offer static CSS files. We are not responsible for loading them into your website.

> But there is no configuration

Configuration for what? 

I'm sorry but you are not providing enough information. 
I get that you want to load a CSS file, but Prism is not responsible for that. Also, what is an "external chain"?

**Comment by fish-uncle** [comment]
Sorry, my English is not very good
Maybe external links are better
I may have written in the wrong place
I want to ask `hexo prism plugin`
I am Sorry:smile:

**Comment by RunDevelopment** [comment]
No problem.

And yes, `hexo-prism-plugin` seems like the right place to ask your question.
