### ISSUE TITLE
1.4.0 release?

### ISSUE THREAD

**Issue by simmerer** [PrismJS/prism-themes#102]
Thanks for all your work! Would love to have another release out soon.

**Comment by RunDevelopment** [comment]
But we released [1.4.0](https://www.npmjs.com/package/prism-themes) in April?

That being said, the [GH releases](https://github.com/PrismJS/prism-themes/releases) weren't up to date, so I fixed that.

**Comment by simmerer** [comment]
🤦 I was only looking at the GH releases page. Thank you!
