### ISSUE TITLE
style prism-vsc-dark-plus doesn't work as expected

### ISSUE THREAD

**Issue by Darfion** [PrismJS/prism-themes#117]
I'll show you how the colors of Visual Studio Code are displayed in prism-vsc-dark-plus. language = jsx

`prism-vsc-dark-plus`
![image](https://user-images.githubusercontent.com/59833414/115518975-9f0bfd80-a23d-11eb-84e6-fb95847bf9b7.png)

`Visual Studio Code`
![image](https://user-images.githubusercontent.com/59833414/115519321-f1e5b500-a23d-11eb-8dd0-68a4c324d97c.png)

I think you can see the difference in colors.

**Comment by RunDevelopment** [comment]
> I think you can see the difference in colors.

I can see that you are using [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2). Prism has [a plugin for this](https://prismjs.com/plugins/match-braces/) if you are interested.

The other differences can all be explained by one thing: semantic analysis.
The syntax highlighting of VSCode is augmented using the information provided by its language servers. In this case, the TS language server does a full-blown semantic analysis of your code to really understand it. This means that the TS language knows the type/scope/const-ness/etc. of very variable/function/class/etc.. VSCode then uses this information to give you [semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide).

Prism does not do any form of semantic analysis. This is why:

- Prism has no idea that `setY` is a function (`setState` might return anything).
- Prism has no idea that `xx` is `const`. 
  Actually, Prism _could_ detect that `xx` is `const` but only at the declaration site. We would not be able to highlight `xx` consistently. E.g. in the snippet `const x = 0; alert(x);`, you (again) need semantic analysis to know that both variables `x` are actually the same variable.
- Prism has no idea that `Yy` is not a class.
  Prism uses a heuristic to detect class names. The JS community largely follows the naming convention of capitalizing class names and Prism uses this for detection. `Yy` is a false positive of this heuristic that is not possible to correct without semantic analysis.

@Darfion I'm sorry to say this but this is the best a syntax highlighter can do without semantic analysis. There is nothing we can do to fix _these_ differences.

I want to emphasize that this applies specifically to the differences you showed. Other differences _might_ be fixable.

**Comment by miliko0022** [comment]
Hello @RunDevelopment. I am using `react-syntax-highlighter`. maybe you know how to include `match-braces` in` react-syntax-highlighter` ?.

**Comment by miliko0022** [comment]
Hello RunDevelopment. I am using `react-syntax-highlighter`. maybe you know how to include `match-braces` in` react-syntax-highlighter` ?.

**Comment by RunDevelopment** [comment]
Hello @miliko0022! I am not familiar with `react-syntax-highlighter`, so I can't really help you, sorry. It seems like they don't support Prism plugins but you might want to [ask them directly](https://github.com/react-syntax-highlighter/react-syntax-highlighter/discussions).

**Comment by miliko0022** [comment]
@RunDevelopment OK thanks
