### ISSUE TITLE
Publish version 1.7.0

### ISSUE THREAD

**Issue by RunDevelopment** [PrismJS/prism-themes#119]
I think it's time for a new version @mAAdhaTTah.

---

@LeaVerou @mAAdhaTTah I could also do the publishing if you gave me those permissions for our npm packages.

**Comment by LeaVerou** [comment]
You should definitely have permission! How could I add you?

**Comment by RunDevelopment** [comment]
I think you just have to to the settings tab of the npm package and enter my name under "Invite maintainer". I'm called "rundevelopment" over on npm too.

**Comment by LeaVerou** [comment]
Done!

**Comment by RunDevelopment** [comment]
You only invited me to `prismjs` but not `prism-themes`... 😅

**Comment by LeaVerou** [comment]
> You only invited me to `prismjs` but not `prism-themes`... 😅

Done! Sorry!

**Comment by RunDevelopment** [comment]
Nice! Thank you Lea!!!
