### ISSUE TITLE
White background coming for c++ symbols

### ISSUE THREAD

**Issue by tbhaxor** [PrismJS/prism-themes#127]
I am using vscode dark plus theme and getting this weird while a background in the `<<` sign.

![image](https://user-images.githubusercontent.com/28386721/126837213-bd62ee9f-08cf-48bf-9d50-83691ede4d71.png)

I checked, same case with `<` and `*`

**Comment by RunDevelopment** [comment]
Looks like you're using VSCode Dark+ on top of [Prism's default theme](https://github.com/PrismJS/prism/blob/master/themes/prism.css). Is that the case?

**Comment by tbhaxor** [comment]
Yes it fixed my issue. Thanks
