### ISSUE TITLE
New release planned in order to use One Light and Dark theme via PrismJS?

### ISSUE THREAD

**Issue by M00nD3v** [PrismJS/prism-themes#133]
I really want to use the newly created themes One Light and Dark, which need a new version to appear in jsDelivr.

Is there already a new version planned to be able to use them via PrismJS, or should I rather look for a workaround to use the themes until a new version is created?

PS: Please don't feel stressed - it would just be awesome to know if it's worth implementing a workaround or if a new version is around the corner.

**Comment by RunDevelopment** [comment]
We currently have a PR improving plugin support for those themes (#134). I will release a new version after this PR has been merged.

**Comment by M00nD3v** [comment]
Awesome. Thank you for your fast reply.

**Comment by RunDevelopment** [comment]
Resolved by 6de4d1dd8be5a4e303a19efba3e969024a73d66a.
