### ISSUE TITLE
Minified CSS?

### ISSUE THREAD

**Issue by hoonweiting** [PrismJS/prism-themes#135]
Currently working on #134, and wow, my file has surpassed 8kB, and I'm still not done! (Though to be fair, I have several lines' worth of comments at the top.) I was wondering if we could provide the minified versions of the CSS. While most of the themes weigh less than 5kB, I still think it'll be helpful overall, especially as Prism prides itself on being small.

I have seen #70 which was unfortunately closed by the OP due to unresponsiveness, as well as https://github.com/PrismJS/prism/pull/2553 which has been pending for over eight months now.

I am also aware of the earlier https://github.com/PrismJS/prism/issues/956 but I really don't think that "most people modify the CSS at least to a degree"... Even if this were the case, providing the minified CSS does not necessarily mean that we have to stop providing the non-minified ones.

I guess what I want to say overall is, we should give users the convenience of having the minified files ready to go (which is in line with Prism's selling point of being really small), while also letting them have the non-minified one if they would rather modify it directly for their own uses.

**Comment by RunDevelopment** [comment]
I'll make a PR adding minified themes.

Regarding themes over at Prism: PrismJS/prism#2553 seems to have gone stale. I'll try to finish it today.

**Comment by hoonweiting** [comment]
Whoa, that's fast! Thank you so much for all your efforts :)
