### ISSUE TITLE
Issues regarding VSC dark+ theme

### ISSUE THREAD

**Issue by M00nD3v** [PrismJS/prism-themes#137]
https://github.com/PrismJS/prism-themes/blob/1e3e8d655802dd24b65a39a4a5637c5ec0c7af72/themes/prism-vsc-dark-plus.css#L48

At this line there is an issue which sets the background-color of inline code-blocks to a light color (#f9f2f4) instead of a dark one like the code-block background-color (#1e1e1e). 

I suggest changing this to a dark color like #1e1e1e to achieve a good contrast between code and background.

Preview of inline code-block: 
![Preview of inline code-block](https://user-images.githubusercontent.com/26168940/132999094-f9549114-8b82-45ea-b057-4d06f315fd10.png)

**Comment by M00nD3v** [comment]
Furthermore I wanted to add that it probably would be better if the font size is the same in every theme.

**Comment by RunDevelopment** [comment]
Regarding font size: Over at PrismJS/prism, we use a `font-size: 1em` for all themes. It might be a good idea to do so here as well.
