### ISSUE TITLE
Custom in babelrc

### ISSUE THREAD

**Issue by Re-taro** [PrismJS/prism-themes#149]
How can I use custom theme in Prism.js, which is setting in .babelrc?

**Comment by RunDevelopment** [comment]
We have a [babel plugin](https://github.com/mAAdhaTTah/babel-plugin-prismjs) that allows you to do that.

**Comment by RunDevelopment** [comment]
Oh, wait. Sorry, I didn't read the "custom" part. The babel plugin currently can't do that. But it should. I opened an issue for you.

I will still keep this issue closed since it has little to do with this library.
