### ISSUE TITLE
VS theme does not work with line numbers.

### ISSUE THREAD

**Issue by AnalogFeelings** [PrismJS/prism-themes#153]
## 🐛 Bug Report

The VS theme does not work with the line numbers plugin, but the default themes included in prism do.

**Comment by RunDevelopment** [comment]
[Line Numbers has CSS](https://github.com/PrismJS/prism/blob/master/plugins/line-numbers/prism-line-numbers.css). Line Numbers work with neither our default themes nor the themes in this repo without its CSS. The reason this might appear not to be so is that our download page automatically includes the CSS of plugins (if they have any). So if you get themes from this repo, you have to link to their CSS yourself.

**Comment by AnalogFeelings** [comment]
Curious, if I use the default themes without including the line numbers CSS, it seems to work fine 🤔

**Comment by RunDevelopment** [comment]
That's not possible. Could you show the theme's CSS you're including?

**Comment by AnalogFeelings** [comment]
I'm just including the default theme from the download page, and XP.css which is a completely unrelated library.

If I swap out the default theme with the VS theme, it stops working. (I haven't tried other themes from this repository, though).

Here's the default theme just in case:
[prism.css.txt](https://github.com/PrismJS/prism-themes/files/8764177/prism.css.txt)

**Comment by RunDevelopment** [comment]
> from the download page

As I said:

> our download page automatically includes the CSS of plugins

When you go to the download page, it automatically adds the Line numbers CSS.

That's because the download page doesn't give you just a theme, it creates a bundle of the CSS of your selected theme + all plugin CSS of the plugins you selected.

**Comment by AnalogFeelings** [comment]
Ah, now I understand. Thanks.
