### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by DominicTobias** [PrismJS/prism-themes#62]
Hi, I noticed this project isn't published to NPM - mind publishing it? thanks

**Comment by charlespeters** [comment]
@DominicTobias in the meantime you can `npm i -S prism-themes@PrismJS/prism-themes`

**Comment by DominicTobias** [comment]
Nice wasn't aware of that syntax

**Comment by LeaVerou** [comment]
Sorry, will `npm publish` today!

**Comment by hason** [comment]
@LeaVerou @Golmote ping

**Comment by LeaVerou** [comment]
Done!
