### ISSUE TITLE
Update npm registry

### ISSUE THREAD

**Issue by breeswish** [PrismJS/prism-themes#66]
Thanks for the great project! Could you publish latest repository to the npm registry? I found that some recent changes (like https://github.com/PrismJS/prism-themes/pull/64) are not in npm.

**Comment by LeaVerou** [comment]
@Golmote @zeitgeist87 I wonder if we can have automated releases in this one, since none of us is that focused on this repo? E.g. every N merged PRs…

**Comment by Golmote** [comment]
It's a nice idea but I have no clue how to do that.

**Comment by GeeWizWow** [comment]
@LeaVerou We're currently hitting an issue which could be resolved by having an up to date version of prism-themes hosted on the npm registry

https://github.com/conorhastings/react-syntax-highlighter/issues/95
https://github.com/conorhastings/react-syntax-highlighter/pull/96

Mind if I start poking around with automated releases using something like Travis CI ?

https://travis-ci.com/

**Comment by LeaVerou** [comment]
Thank you!
We do the same for the normal Prism repo too :)

**Comment by GeeWizWow** [comment]
Ah, I see, fantastic!

btw you have what looks to be an api secret key in your travis.yml file (main prism repo) maybe it's on purpose ? 😧

**Comment by LeaVerou** [comment]
> btw you have what looks to be an api secret key in your travis.yml file (main prism repo) maybe it's on purpose ? 😧

Wow, that's really weird. And `git blame` says I did it. 😕 
I'm pretty sure I just followed some tutorial from somewhere.
@apfelbox do you remember anything related to this?

**Comment by GeeWizWow** [comment]
Although hold on... it looks like that might be ok after all

https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml

**Comment by apfelbox** [comment]
@LeaVerou nope, sorry. We only installed the testing side of Travis back then, the deployment part came later and I wasn't involved with that.

But as @GeeWizWow already found out there is nothing wrong with your `.travis.yml`: the `secure:` part tells you, that you are indeed using Travis' encrypted variables – so you actually encrypted the variables with a secret only you and Travis know (and without this secret the key can't be decrypted).

**Comment by GeeWizWow** [comment]
Days since spooking people for nothing: 0

As far as i can tell, the steps for enabling automatic deployment in this
repo would be to commit the same .travis.yml file as in prism here and to
change the repo name in the deploy section.

The only item i'm unsure about is if the encrypted env variable is account
or project specific.

**Comment by mAAdhaTTah** [comment]
Opened a PR to get travis on this (#73).

**Comment by mAAdhaTTah** [comment]
Been a little while, but just published v1.1.0!
