### ISSUE TITLE
Dracula theme (do not confound with Darcula theme)

### ISSUE THREAD

**Issue by gusbemacbe** [PrismJS/prism-themes#74]
Hello,

I created a Dracula theme for Prism.js in my old repository 3 years ago and stopped due to my college, but I saw someone wanting to use my theme for Prismjs yesterday, then yesterday I have fixed all bugs and finished my job. Now I transferred it to the official repository of Dracula Themes.

You can check: https://github.com/dracula/prism.

Do not confound the Dracula theme with Darcula theme. Their themes plaettes are different.

**Comment by Golmote** [comment]
Hi! If you'd like this theme to be included here, you'll need to make a PR, not an issue.
Your PR should include your CSS file, a small screenshot and the updated README. See #72 for a recent example.
