### ISSUE TITLE
Docs for creating prism themes.

### ISSUE THREAD

**Issue by fakeinc** [PrismJS/prism-themes#82]
Hi. I'm deciding to port my color scheme for JetBrains to prismjs. However, it seems there has not been any official documentation now. I tried reading source code of these themes. However, I'm afraid that I'd miss some elements to theme. So I need the docs. Thank you.

**Comment by RunDevelopment** [comment]
The [FAQ](https://prismjs.com/faq.html#how-do-i-know-which-tokens-i-can-style-for) on the Prism website explains this.

The little script is quite helpful but it [won't show you everything](https://github.com/PrismJS/prism/issues/1975#issue-467733528). 
In the meantime, I can just say that you could you the [tests](https://github.com/PrismJS/prism/tree/master/tests/languages) of the given language as the tests usually cover almost all tokens a language supports.

That being said, not every language uses every token name, so by just covering the most common should be enough. You can see which token names that are in the [Prism default themes](https://github.com/PrismJS/prism/tree/master/themes).

**Comment by fakeinc** [comment]
@RunDevelopment Thanks! I'll check these out.
