### ISSUE TITLE
Release the latest package on npm?

### ISSUE THREAD

**Issue by ahmadawais** [PrismJS/prism-themes#85]
Users have been asking me to add theme here and I did.

Can you folks release the latest pkg on npm? 

https://www.npmjs.com/package/prism-themes

It's outdated.

**Comment by RunDevelopment** [comment]
Yeah, that'd be great. 
@mAAdhaTTah

But could we get #79 before that? It's just sitting there, all alone, rebased, and ready to merge.

**Comment by mAAdhaTTah** [comment]
Approved that. There's also #84 for screenshots, but there's some massaging to be done there.

**Comment by RunDevelopment** [comment]
Yes, but #84 is only a readme change, so I don't think that we need to delay the release. 

Also, could please also merge #79. I'm not listed as a collaborator for this project, so I can't.

**Comment by mAAdhaTTah** [comment]
Done. Will release when I'm home.

The README change might be nice for npm but not a requirement.

**Comment by RunDevelopment** [comment]
Nice!

> The README change might be nice for npm but not a requirement.

Exactly what I was thinking.

I'll review #84, so we can merge it then.

**Comment by mAAdhaTTah** [comment]
Published.
