### ISSUE TITLE
Can you make a new release?

### ISSUE THREAD

**Issue by ArjanvHugten** [PrismJS/prism-themes#96]
Hi,

Is it possible to create a new release? I really like the VS code dark theme and want to use it from the NPM package. 

Thanks!

**Comment by RunDevelopment** [comment]
@mAAdhaTTah

**Comment by mAAdhaTTah** [comment]
I'll probably be able to do that this weekend. @RunDevelopment Do we want to cut a release for Prism core as well?

**Comment by RunDevelopment** [comment]
Sure.

**Comment by mAAdhaTTah** [comment]
Sorry for the delay, but this is done.
